
#define TRANSPORT_HDR_MGC 29517
#define TRANSPORT_SENDER_SIZE 5

//
// Transport error codes
//
#define TRANSPORT_ERR_OK 0
#define TRANSPORT_ERR_ZMQ -64000
#define TRANSPORT_ERR_BAD_SIZE -64001
#define TRANSPORT_ERR_BAD_HEADER -64002
#define TRANSPORT_ERR_BAD_PARTSCOUNT -64003
#define TRANSPORT_ERR_SOCKET_CLOSED -64004
#define TRANSPORT_ERR_NULL_DATA -64005
#define TRANSPORT_ERR_NULL_DEALERID -64006

#define PROTOCOL_ID_NONE '\0'
